AWSTemplateFormatVersion: "2010-09-09"
Description: Receive Cloudformation events

Parameters:
  OrganizationId:
    Type: String
    Description: "ID of AWS organization"
  EventBusName:
    Type: String
    Description: "Name of the event bus"

Resources:
  CfnMonitoringEventBus:
    Type: "AWS::Events::EventBus"
    Properties:
      Name: !Ref EventBusName

  EventBusPolicy:
    Type: "AWS::Events::EventBusPolicy"
    Properties:
      EventBusName: !Ref CfnMonitoringEventBus
      StatementId: "AllowOrgEvents"
      Action: "events:PutEvents"
      Principal: "*"
      Condition:
        Type: "StringEquals"
        Key: "aws:PrincipalOrgID"
        Value: !Ref OrganizationId

  CfnEventsLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/aws/events/cloudformation-monitoring"
      RetentionInDays: 7

  CfnEventsRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Log CFN events"
      EventBusName: !Ref CfnMonitoringEventBus
      EventPattern:
        source:
          - "aws.cloudformation"
      State: "ENABLED"
      Targets:
        - Id: CloudWatchLogs
          Arn: !GetAtt CfnEventsLogGroup.Arn
